# This workflow is derived from the "Python application" workflow

name: MOTHER 3 to MIDI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        loop:
        - name: -NOLOOP
          args: 
        - name: 
          args: --loop
        mode: [MIDI, MSGS, GM, GM2, SC88]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Mido
      run: |
        python -m pip install --upgrade pip
        pip install mido
    - name: Generate files
      run: |
        python fixosv.py --mode=${{ matrix.mode }} ${{ matrix.loop.args }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: OSV${{ matrix.mode }}${{ matrix.loop.name }}
        path: ./OSVMIDI
